# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A random walk Metropolis sampler using Rcpp
#' @description A random walk Metropolis sampler for generating the standard Laplace distribution using Rcpp
#' @param sigma the stand deviation of proposal distribution to the random walk Metropolis chains 
#' @param x0 the initial point
#' @param N the number of produced values in chain
#' @return a random sample of \code{the standard Laplace distribution}
#' @useDynLib SC19057
#' @examples
#' \dontrun{
#' out <- rwMC(2.0,20.0,2000)
#' plot(out[,1], type="l", main='rwMC(sigma=2)', ylab="x",xlab = "")
#' }
#' @export
rwMC <- function(sigma, x0, N) {
    .Call('_SC19057_rwMC', PACKAGE = 'SC19057', sigma, x0, N)
}

